version: '3.5'
services:
  open-dataverse:
    build: .
    container_name: "open-dataverse"
    ports:
     - "4000:4000"
    volumes:
     - .:/app
    environment:
     - ENV=development
     - PORT=4000
     - DB=mongodb://mongodb:27017/dataverse
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=dataverse
    volumes:
      - ./data/db:/usr/data/db
    ports:
        - 27017:27017
    # command: mongod --smallfiles --logpath=/dev/null # --quiet
networks: 
  default:
    name: open-dataverse